version: '3.7'

services:

  web:
    container_name: lumen
    build:
      context: ./docker
    links:
      - mysql
    networks:
      - servers
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=servermail
      - MYSQL_USER=servermail
      - MYSQL_PASSWORD=servermail
    networks:
      - servers
    volumes:
        - db-mysql:/var/lib/mysqlb

networks:
  servers:
    external: true
volumes:
  db-mysql:
